### ISSUE TITLE
Html paste  failed with images & icon 

### ISSUE THREAD

**Issue by fareedkh** [cetinkaya/pastefromhtml#10]
hi,

thanks for very use full plug-in ,
unfortunately it failed while any image media is included in  html , with popup error 'close'
Python 3.8.2 is installed .

![Selection_005](https://user-images.githubusercontent.com/529224/79071180-a1b34900-7cf3-11ea-89f6-92014d870e49.png)
 
Thank you.
-fredkh

**Comment by fareedkh** [comment]
following error on Ubuntu 19x 

![unnamed](https://user-images.githubusercontent.com/529224/79071941-cd383280-7cf7-11ea-9c50-ec95fb46d839.png)

**Comment by fareedkh** [comment]
Hi,

strange , Issue is resolve by it self. 
computer was restarted for couple of time.

Thanks any way, for a nice plug-in.

-fareedkh

**Comment by cetinkaya** [comment]
Thank you for reporting these issues. There was indeed a bug in the plugin. 

The popup message with "is a directory: ..." did indeed show up when I tried the plugin for copying `img` tags with empty `src` attributes. An example case:

```html
a
<img src="" alt="test"/>
b
```
I tried to fix this bug and hopefully the change in bb9ca20 resolves this issue. 

I am not sure about the first issue with the empty popup message showing only the close button. Do you remember which website did you try the plugin for?

**Comment by mquan86** [comment]
I'm not sure if I have the same issue with the first reported, but I have empty popup very similar.

Example web: https://lazyadmin.nl/powershell/microsoft-teams-uninstall-reinstall-and-cleanup-guide-scripts/

I copy any image from there, paste and get empty popup. From log, it complain about SSL certificate:

```
DEBUG: Action: pastefh
DEBUG: Exception during action: pastefh
Traceback (most recent call last):
  File "urllib/request.py", line 1346, in do_open
  File "http/client.py", line 1279, in request
  File "http/client.py", line 1325, in _send_request
  File "http/client.py", line 1274, in endheaders
  File "http/client.py", line 1034, in _send_output
  File "http/client.py", line 974, in send
  File "http/client.py", line 1448, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build/venv/lib/python3.9/site-packages/zim/actions.py", line 159, in _on_activate
  File "build/venv/lib/python3.9/site-packages/zim/actions.py", line 130, in __call__
  File "C:\Portable\data\zim\plugins\pastefromhtml\__init__.py", line 93, in pastefh
    buffer.insert_at_cursor(h.to_zim(data, folder))
  File "C:\Portable\data\zim\plugins\pastefromhtml\htmlcdparser.py", line 461, in to_zim
    self.feed(html_str)
  File "C:\Portable\Zim\html\parser.py", line 110, in feed
    self.goahead(0)
  File "C:\Portable\Zim\html\parser.py", line 170, in goahead
    k = self.parse_starttag(i)
  File "C:\Portable\Zim\html\parser.py", line 344, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "C:\Portable\data\zim\plugins\pastefromhtml\htmlcdparser.py", line 248, in handle_starttag
    get_url(src, self.folder.path + "/" + img_name)
  File "C:\Portable\data\zim\plugins\pastefromhtml\htmlcdparser.py", line 34, in get_url
    f.write(urllib.request.urlopen(req).read())
  File "urllib/request.py", line 214, in urlopen
  File "urllib/request.py", line 517, in open
  File "urllib/request.py", line 534, in _open
  File "urllib/request.py", line 494, in _call_chain
  File "urllib/request.py", line 1389, in https_open
  File "urllib/request.py", line 1349, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
ERROR: None
DEBUG: Running ErrorDialog
DEBUG: Folder change detected: <zim.notebook.layout.FilesAttachmentFolder object at 0x000001ff983c7610>
```

**Comment by cetinkaya** [comment]
@mquan86 I don't seem to have any problem with the website you mentioned on Linux. Do you see a similar problem when you are trying to paste images from other websites with "https" urls?

I suspect that this issue may be related to the issue discussed here:
https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

**Comment by mquan86** [comment]
@cetinkaya, I see the same error on all https url so far. I forget to mention, I use Windows 10 which seems the problem.

The link you provided is really helpful. I'm not fluent in Python, but from that discussion, I guess the problem may be multiple factors:
- The behavior may be different between Python version and platform.
- Zim build for Windows seems doesn't use the installed Python but some embed. (#12)

Base on that I found a workaround for Windows environment:
- Download CPython, copy Lib\site-packages\certifi to Zim root folder
- Modify plugins\pastefromhtml\htmlcdparser.py as below (add new import and modify the request download)

from: 
```
import os
...
#download file of url
def get_url(url, name):
    ...
    f.write(urllib.request.urlopen(req).read())
    ...
  ```
to:
```
import os
import certifi
import ssl
...
#download file of url
def get_url(url, name):
    ...
    f.write(urllib.request.urlopen(req,context=ssl.create_default_context(cafile=certifi.where())).read())
    ...
```

References:
- https://stackoverflow.com/a/48134650
- #12 

Do you want me to open separated case to improve this somehow? (as the first report of this ticket is Linux environment, so most likely not the same error)
