### ISSUE TITLE
Can't load pastefromhtml plugin due to No module named 'html.parser'

### ISSUE THREAD

**Issue by mquan86** [cetinkaya/pastefromhtml#12]
I have Zim 0.74.3 installed as portable (Windows 10) and I'm trying install plugin pastefromhtml 
However in Plugin tab, say fail to load the plugin ("There was a problem loading this plugin")

In debug log it seems fail or missing module 'html.parser'?
Do you have any idea how to fix it?

```
ERROR: Could not load plugin pastefromhtml
Traceback (most recent call last):
  File "build/venv/lib/python3.9/site-packages/zim/gui/preferencesdialog.py", line 403, in __init__
  File "build/venv/lib/python3.9/site-packages/zim/plugins/__init__.py", line 473, in get_plugin_class
  File "build/venv/lib/python3.9/site-packages/zim/utils.py", line 36, in get_module
  File "C:\Portable\data\zim\plugins\pastefromhtml\__init__.py", line 20, in <module>
    from .htmlcdparser import HTMLCDParser
  File "C:\Portable\data\zim\plugins\pastefromhtml\htmlcdparser.py", line 15, in <module>
    from html.parser import HTMLParser
ModuleNotFoundError: No module named 'html.parser'
```

**Comment by mquan86** [comment]
Hi, thanks for dedicated resolution. I actually found that we can put those files from CPython to root folder of Zim and it automatically load without any modification. I could enable the plugin but seems the plugin doesn't do anything (doesn't work). At that time I'm not sure if that is correct way to fix or not, so I wait for your official resolution one.
Today I tried with yours and it has the same result able to enable the plugin, but the plugin doesn't work similar.

This is the first time I use your plugin so I'm not sure I use it correctly or the plugin is actually broken somehow. Do you want me open separated case for that or discuss it here?

I summary your resolution here in case I need in the future:
### Option 1: (your official one)
- Downloads CPython (example: https://github.com/python/cpython/archive/refs/tags/v3.9.14.zip)
- From CPython, copy 2 files/folder below to inside plugin folder of pastefromhtml:
  - Lib\html
  - Lib\_markupbase.py
- So now the folder plugin is like below: 
```
| 
|
\---pastefromhtml
    |   htmlcdparser.py
    |   parser.py
    |   _markupbase.py
    |   __init__.py
    |
    \---html
            entities.py
            parser.py
            __init__.py
```

- Modify file ...\pastefromhtml\htmlcdparser.py
  - from:
```
from html.parser import HTMLParser
from html.entities import name2codepoint
```
  - to:
```
from .html.parser import HTMLParser
from .html.entities import name2codepoint
```
- Modify file ...\pastefromhtml\html\parser.py
  - from:
`import _markupbase`
  - to:
`from .. import _markupbase`

### Mine: (no guarantee)
- Download CPython and copy below file/folder from CPython to root Zim folder:
  - `Lib\html`
  - `Lib\_markupbase.py`
- No need to modify any files as Zim auto load it somehow.

**Comment by mquan86** [comment]
Thanks. Close the case as the workaround is ok and you already #13 for improvement. Will report the plugin doesn't work issue in separated ticket.
